// HRM
export const COMMON_NOTE_SHEET = 'COMMON_NOTE_SHEET';
export const HRM_COMMON_CIRCULAR = 'HRM_COMMON_CIRCULAR';
export const HRM_CASUALITY_WRITTEN_REGISTER = 'HRM_CASUALITY_WRITTEN_REGISTER';

// Security
export const CLR_GATE_PASS_APPLICATION_DETAIL = 'CLR_GATE_PASS_APPLICATION_DETAIL';
export const CLR_GATE_PASS_APPLICATION_MASTER = 'CLR_GATE_PASS_APPLICATION_MASTER';

// Finance
export const FIN_RV = 'FIN_RV';
export const FIN_PESNSION_REFERENCE_DOCUMENT = 'FIN_PESNSION_REFERENCE_DOCUMENT';

// Ration
export const RATION_FAMILY_INFO = 'RAW_EMPLOYEE_FAMILY_INFORMATION';
export const RATION_SALE_MASTER = 'RAW_RATION_SALE_MASTER';
export const RAW_EMPLOYEE_PERSONAL_INFORMATION = 'RAW_EMPLOYEE_PERSONAL_INFORMATION';

// Budget
export const BUDGET_BILL = 'BUDGET_BILL';

// Recruitment
export const REC_RECRUITMENT_REFERENCE_ACTIVITY = 'REC_RECRUITMENT_REFERENCE_ACTIVITY';








